In [1]:
import numpy as  np

x=[[1,2],[3,4]]
y=[[1,2],[2,3]]

#z= [[2,4]],[5,7]]

nx= np.array(x)
ny= np.array(y)

nx + ny # add



array([[2, 4],
       [5, 7]])

In [2]:
nx - ny 


array([[0, 0],
       [1, 1]])

In [3]:
nx * ny # element-wise multi


array([[ 1,  4],
       [ 6, 12]])

In [4]:
np.arange(10)   # 0 to 9


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
a= np.arange(-10,10,.01)#
print(a)
print(a.shape)
print(a.dtype)

[-10.    -9.99  -9.98 ...   9.97   9.98   9.99]
(2000,)
float64


In [6]:
a.tolist()# not recommended

[-10.0,
 -9.99,
 -9.98,
 -9.97,
 -9.96,
 -9.950000000000001,
 -9.940000000000001,
 -9.930000000000001,
 -9.920000000000002,
 -9.910000000000002,
 -9.900000000000002,
 -9.890000000000002,
 -9.880000000000003,
 -9.870000000000003,
 -9.860000000000003,
 -9.850000000000003,
 -9.840000000000003,
 -9.830000000000004,
 -9.820000000000004,
 -9.810000000000004,
 -9.800000000000004,
 -9.790000000000004,
 -9.780000000000005,
 -9.770000000000005,
 -9.760000000000005,
 -9.750000000000005,
 -9.740000000000006,
 -9.730000000000006,
 -9.720000000000006,
 -9.710000000000006,
 -9.700000000000006,
 -9.690000000000007,
 -9.680000000000007,
 -9.670000000000007,
 -9.660000000000007,
 -9.650000000000007,
 -9.640000000000008,
 -9.630000000000008,
 -9.620000000000008,
 -9.610000000000008,
 -9.600000000000009,
 -9.590000000000009,
 -9.580000000000009,
 -9.57000000000001,
 -9.56000000000001,
 -9.55000000000001,
 -9.54000000000001,
 -9.53000000000001,
 -9.52000000000001,
 -9.51000000000001,
 -9.50000000000001,
 -

In [7]:
b= np.linspace(1,100,225, dtype=int)
# print(b)
print(b.shape)
b.reshape(15,15)

(225,)


array([[  1,   1,   1,   2,   2,   3,   3,   4,   4,   4,   5,   5,   6,
          6,   7],
       [  7,   8,   8,   8,   9,   9,  10,  10,  11,  11,  12,  12,  12,
         13,  13],
       [ 14,  14,  15,  15,  16,  16,  16,  17,  17,  18,  18,  19,  19,
         20,  20],
       [ 20,  21,  21,  22,  22,  23,  23,  23,  24,  24,  25,  25,  26,
         26,  27],
       [ 27,  27,  28,  28,  29,  29,  30,  30,  31,  31,  31,  32,  32,
         33,  33],
       [ 34,  34,  35,  35,  35,  36,  36,  37,  37,  38,  38,  39,  39,
         39,  40],
       [ 40,  41,  41,  42,  42,  42,  43,  43,  44,  44,  45,  45,  46,
         46,  46],
       [ 47,  47,  48,  48,  49,  49,  50,  50,  50,  51,  51,  52,  52,
         53,  53],
       [ 54,  54,  54,  55,  55,  56,  56,  57,  57,  58,  58,  58,  59,
         59,  60],
       [ 60,  61,  61,  61,  62,  62,  63,  63,  64,  64,  65,  65,  65,
         66,  66],
       [ 67,  67,  68,  68,  69,  69,  69,  70,  70,  71,  71,  72,  72,
       

In [8]:
b.reshape(3,5,5,3) # 4d array

array([[[[  1,   1,   1],
         [  2,   2,   3],
         [  3,   4,   4],
         [  4,   5,   5],
         [  6,   6,   7]],

        [[  7,   8,   8],
         [  8,   9,   9],
         [ 10,  10,  11],
         [ 11,  12,  12],
         [ 12,  13,  13]],

        [[ 14,  14,  15],
         [ 15,  16,  16],
         [ 16,  17,  17],
         [ 18,  18,  19],
         [ 19,  20,  20]],

        [[ 20,  21,  21],
         [ 22,  22,  23],
         [ 23,  23,  24],
         [ 24,  25,  25],
         [ 26,  26,  27]],

        [[ 27,  27,  28],
         [ 28,  29,  29],
         [ 30,  30,  31],
         [ 31,  31,  32],
         [ 32,  33,  33]]],


       [[[ 34,  34,  35],
         [ 35,  35,  36],
         [ 36,  37,  37],
         [ 38,  38,  39],
         [ 39,  39,  40]],

        [[ 40,  41,  41],
         [ 42,  42,  42],
         [ 43,  43,  44],
         [ 44,  45,  45],
         [ 46,  46,  46]],

        [[ 47,  47,  48],
         [ 48,  49,  49],
         [ 50,  50,  5

In [9]:
np.random.rand(3,3 )# random

array([[0.94339159, 0.09845476, 0.27862462],
       [0.50198837, 0.74284152, 0.33575177],
       [0.05440031, 0.95638415, 0.85205064]])

In [10]:
np.random.randint(1,100)

88

In [11]:
# 100 element array of random integers between 1 to 10
np.random.randint(1,10,100)
print(x)
print('first element:',x[0])
print('last element:',x[-1])
print('first 6 element:',x[:6])
print('last 6 elements:',x[-6:])


[[1, 2], [3, 4]]
first element: [1, 2]
last element: [3, 4]
first 6 element: [[1, 2], [3, 4]]
last 6 elements: [[1, 2], [3, 4]]
